### ISSUE TITLE
FBUI: reload UI and observers on page load

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#100]
When navigating in FB the content script is only loaded once. Therefore ribbons and mutationobserver are not reinjected.

**Comment by iamolivinius** [comment]
Mutationobserver needs to trigger The inject
Am 12.05.2015 7:36 nachm. schrieb "Felix" <notifications@github.com>:

**Comment by dharma-guardian** [comment]
Jep, but I right now I observe only the parts of FB which are loaded with new content. To observe every change and check if it should be reinjected seems a bit to much. I will look for other options first.
