### ISSUE TITLE
Quick Survey on loggin/loggoff (engage/leave)

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#103]
Have a short survey window pop up, every time/or sample random times when a user opens a Facebook page and leaves a Facebook page.

By “open”, it could be logging in, or simply return to an already logged-in FB page; by “leave”, it could be logging off FB, or going to another webpage/computer window for a period of time that exceeds a threshold without actively logging off FB.
See here for status --> #113 

The survey could be in the form of a pop-up window, or a window in ROSE interface (like the diary window), even a link to an external survey. The goal of the survey is to sample the attentional states of the participants (but not over burden them) right before they start to use FB and right after they are done with using Facebook (e.g., focused, bored, relaxed, frustrated, etc.). 

- [x] sidebar in fb tab is used with survey 1
- [x] dismiss button
- [x] a html overlay or new tab/window with survey 2

**Comment by dharma-guardian** [comment]
Right now a minimal solution would be to specify loggin/loggoff and trigger a modal/pop-up with a link to rose-diary or a survey service.

It still questionable how precisely we can determine the leave interaction. Further we would need to find useful intervals for survey to pop up.

**Comment by YiranWangPARC14** [comment]
A tentative requirement:

1. Whenever the user's browser is open (even in background, or minimized), send short survey 1 roughly every hour.

2. If the user logs onto FB, or return to an already open FB page, send short survey 1.

3. If the user logs out of FB, or leave FB for more than 2 minutes, send short survey 2.

Short survey 1:

On a scale of 1(low) – 9(high):
1) How well were you concentrating?
2) Did you find the activity interesting?
3) Did you enjoy what you were doing?

Short survey 2:

Rate the following statements using the following scale (1= Strongly disagree, 5 = Strongly agree), which reflects your experience on Facebook JUST NOW.
1) It seems I am ‘running on automatic’ when using Facebook, without much awareness of what I am doing.
2) I rush through activities (e.g., posting status updates, commenting, launching apps, joining groups) on Facebook without being really attentive to them.
3) I quickly check updates from Facebook without being aware that I am using it.

**Comment by iamolivinius** [comment]
```
        {
            "type": "window",
            "date": 1433259592329,
            "value": {
                "open": false,
                "active": false
            }
        }
```

**Comment by dharma-guardian** [comment]
One possibility

Survey 1 condition:   

if active==true and time_passed_1>constant_value
do
  show survey1
  set time_passed_1=0
  showed_survey_1=true

Survey 2 condition:

if active=false and showed_survey_1==true
do
  show survey2
  set showed_survey_1=false

**Comment by dharma-guardian** [comment]
We have to find a way how to ask the user to do the small survey. (Pass a link to survey monkey)
How can easily show the survey without too much distraction?

**Comment by dharma-guardian** [comment]
If we use an external service for the survey, how can we link to a specific participant?

**Comment by dharma-guardian** [comment]
Split this issue into:

1. Tracking change of activity state (active / not active on fb) 
2. Providing a short survey on trigger in 1

**Comment by YiranWangPARC14** [comment]
If we were to use an external service (e.g., survey monkey), we might need to ask them to input a user id or name in every survey, which adds extra efforts, in addition to having to go out of the site and come back. So if we can do implement it as part of ROSE, such as a pop up window in the browser or the side bar, and the content is stored in the json file, that would be ideal.

**Comment by dharma-guardian** [comment]
We will have a look into that, but there maybe is a way to transmit a user id to the survey or generate a unique survey link for every participant or something else to automatize. Letting the participants fill that out themselves is no option with the frequency of the surveys.

**Comment by iamolivinius** [comment]
If necessary it's also possible to track the login status very easily

**Comment by apoller** [comment]
If you can simply include it as a further metric without much effort then it's okay from my side.

**Comment by dharma-guardian** [comment]
We should think about, if this belongs to an extractor or the activity tracker.

**Comment by iamolivinius** [comment]
Maybe we need to create a extractor to track login status :)

**Comment by dharma-guardian** [comment]
that’s what i thought :)

**Comment by dharma-guardian** [comment]
Use the sidebar for the survey on engaging with fb #141

**Comment by dharma-guardian** [comment]
both surveys plus dismiss button implemented
