### ISSUE TITLE
Improve Release File Size

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#107]
The release package, as well as Rose inside the browser (background-/cotent-script) should be held small to infer as less as possible with the participant.
![bildschirmfoto 2015-05-20 um 23 26 01](https://cloud.githubusercontent.com/assets/1899308/7736986/22cfab48-ff48-11e4-8759-56e848e41af4.png)
Possible Improvements:
* try to exclude unnecessary parts of ember in ui
* build a minimal bundle of forge.js

**Comment by iamolivinius** [comment]
use `ember build -prod` instead of `ember build` to improve file size:

5mb -> 1.5mb
