### ISSUE TITLE
Fetch Observer in Study Creator from Repository

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#110]
- [x] Fingerprint input field
* [x] fetch new observers/extractors
* [x] verify fingerprint and signatures
- [x] Toggle single observer
- [x] visual feedback for verification of observers
- [x] toggle in-/secure mode
- [x] visual feedback for insecure mode

**Comment by iamolivinius** [comment]
Finger print implemented in 007e79f

**Comment by dharma-guardian** [comment]
It is working.  A few things:

- [ ] Repositories should be removed/replaced, when you change the repositoryURL
- [ ] Update interval?

**Comment by iamolivinius** [comment]
Try to be more precise when you write "use cases"
Am 07.10.2015 2:08 nachm. schrieb "Felix" <notifications@github.com>:

**Comment by dharma-guardian** [comment]
I will..
<img width="769" alt="bildschirmfoto 2015-10-07 um 14 16 22" src="https://cloud.githubusercontent.com/assets/1899308/10337197/7995daaa-6cfe-11e5-81b9-112ac39acd62.png">

**Comment by iamolivinius** [comment]
Just finished https://github.com/secure-software-engineering/rose/issues/110#issuecomment-146177859 in latest master.
