### ISSUE TITLE
Wording Rose3

### ISSUE THREAD

**Issue by eppfel** [secure-software-engineering/rose#115]
- [x] RoseUI
  - [x] Wizard
  - [x] Settings: update interval
  - [x] Study Creator: Network / Observer list
  - [x] Application log
  - [x] Observer editor
  - [x] Data Extractor
  - [x] Dashboard
- [x] FacebookUI
- [x] Readme.md
- [ ] german in general

**Comment by apoller** [comment]
I also need to change the text for the wizard and the german text.

Please add labels for the wizard text, including the buttons

**Comment by dharma-guardian** [comment]
Toggles in settings should be "activate/deactive" or "on/off"

**Comment by iamolivinius** [comment]
Please settle on one or the other

**Comment by dharma-guardian** [comment]
on/off it is then.

**Comment by iamolivinius** [comment]
OK... Done! Installation wizard will be next.

**Comment by dharma-guardian** [comment]
labels for wizard in de7a802c8bb7540e463ef7efc3722170f80f3dc7

**Comment by iamolivinius** [comment]
Needs more wording for the following keys: 

- [ ] settings.manualUpdate
- [ ] settings.manualUpdateLabel
- [ ] action.reset
- [ ] action.update

**Comment by YiranWangPARC14** [comment]
Oliver,

Did you mean that you need more updates on wording for the beta4 version?

I didn't see the release of the beta4 until now. I installed it, but I
couldn't pass the configuration stage, as the UI does not let me submit the
default setting. There is only one button "choose a file" while no option
to submit/confirm the default config. Any suggestion on how to bypass the
config page?

Thanks!
Yiran

**Comment by dharma-guardian** [comment]
hey Yiran, the default option is a mock up right now. You have to download the default configurations here: https://github.com/secure-software-engineering/rose/releases/tag/3.0.0beta4
It's the file with the .json ending.
Oliver wanted to inform Andreas, that there are text labels which still are dummy text.

**Comment by YiranWangPARC14** [comment]
Felix,

Thanks. I wasn't sure if I should be wording those dummy text, or update it
(if necessary) once you guys have wording for them. Please let me know.

Yiran

**Comment by apoller** [comment]
Done for English.
Yet text required for German.

**Comment by iamolivinius** [comment]
Missing translations in: 

- [ ] study creator
- [ ] settings

**Comment by dharma-guardian** [comment]
@apoller 
![bildschirmfoto vom 2015-10-23 16 08 19](https://cloud.githubusercontent.com/assets/1899308/10694802/86d240f6-79a0-11e5-8a56-561566680534.png)
![bildschirmfoto vom 2015-10-23 16 08 35](https://cloud.githubusercontent.com/assets/1899308/10694805/88812c3c-79a0-11e5-86f3-73931d1ca797.png)

**Comment by apoller** [comment]
Currently nothing to do here, made several changes with 58dbd76. However, I will leave this ticket open. We can later ask @YiranWangPARC14 to proofread the newly added labels.

**Comment by YiranWangPARC14** [comment]
Yes, please email me if you need to proofread new materials.

On Wed, Feb 3, 2016 at 10:13 AM, apoller <notifications@github.com> wrote:

> Currently nothing to do here, made several changes with 58dbd76
> <https://github.com/secure-software-engineering/rose/commit/58dbd769e1b6a59d07c27a70f3317ee378bfc10a>.
> However, I will leave this ticket open. We can later ask @YiranWangPARC14
> <https://github.com/YiranWangPARC14> to proofread the newly added labels.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/secure-software-engineering/rose/issues/115#issuecomment-179385656>
> .
>



-- 
Best,
Yiran
