### ISSUE TITLE
Chrome automatically disables ROSE

### ISSUE THREAD

**Issue by LKocksch** [secure-software-engineering/rose#130]
With my little technical knowledge I couldn´t fix that (wont be different for our participants). Did I do something wrong? 
Also, Chrome only suggests to contact the developers to fix it ( and thus entry your extension to the Chrome Web Store). 
![chrome disables extensions](https://cloud.githubusercontent.com/assets/5921719/8650185/3b80c70a-2971-11e5-810c-1d88465b4290.png)

**Comment by iamolivinius** [comment]
Open the following link in Google Chrome: chrome://extensions/

Click the checkbox to enable the extension again.

Any idea under which circumstances rose was disabled?

**Comment by LKocksch** [comment]
No can do... It´s grayed out so that I can´t klick on the checkbox (see screenshot)
![rose checkbox](https://cloud.githubusercontent.com/assets/5921719/8650700/d309c3b2-2974-11e5-9168-4e8d3de96d8e.png)

Don´t know the circumstances either. I installed ROSE last week, hung out on Chrome for a day and tried to open it this morning when it showed me the above mentioned screen. Sorry :/

**Comment by iamolivinius** [comment]
Which version of chrome?

**Comment by LKocksch** [comment]
Version 43.0.2357.132 m (According to Chrome the latest) on Windows 7 64 bit

**Comment by iamolivinius** [comment]
What a lovely feature :heart: 

I can't find out when Chrome decides to disable a non-WebStore extension but obviously they do.

This affects Windows and OS X, Linux is unaffected. Can't find an easy way to re-enable extensions.

**Comment by LKocksch** [comment]
Indeed :(

**Comment by apoller** [comment]
I don't mind uploading it to Chrome Webstore.
Just check the conditions we have to meet for an upload.

**Comment by dharma-guardian** [comment]
A quick work around for further testing @LKocksch is to activate developer mode (Entwicklermodus):
<img width="905" alt="bildschirmfoto 2015-07-14 um 09 27 30" src="https://cloud.githubusercontent.com/assets/1899308/8668402/e58f2ad6-2a0a-11e5-83ef-5561496c30cc.png">

**Comment by LKocksch** [comment]
Yea, I know. I tried this as well. Doesn´t work with Windows...

**Comment by dharma-guardian** [comment]
Damn it Google...

**Comment by iamolivinius** [comment]
Closed in favor of #132

**Comment by dharma-guardian** [comment]
@LKocksch until we have a version in the Chrome Web Store, this could work for you: http://superuser.com/a/768154

**Comment by LKocksch** [comment]
Thank you! Xxx
