### ISSUE TITLE
Create process to publish ROSE extension to Chrome Web Store and Mozilla add-ons

### ISSUE THREAD

**Issue by iamolivinius** [secure-software-engineering/rose#132]

**Comment by iamolivinius** [comment]
This becomes more and more important due to the fact that FF 43 won't run unsigned extensions anymore. This can not be overwritten withing stable user builds of FF. Nevertheless in nightly and developer versions of FF there is an option flag: `xpinstall.signatures.required`

**Comment by iamolivinius** [comment]
New tasks like `gulp sign` and `gulp publish` need to be implemented in build tool.

**Comment by apoller** [comment]
I registered to both Google Chrome Webstore and Firefox Add-ons. I also paid necessary fees. So in principle I can now upload file to both stores.

However, before we have to clarify how we handle signing keys. Can you please look into the code signing details for both store and then propose how we can safely handle keys. We have a further OpenPGP card we could use for signing, or we use the one Felix stores currently.

**Comment by iamolivinius** [comment]
publishing process in a few words:

Firefox: develop extension - create xpi file - upload xpi to AMO (mozilla add-ons) - mozilla will review extension - if review successful mozilla signs extension and publishes extension or returns the developer a signed package

Chrome: develop extension - package extension with private key file (pem file) - upload to chrome web store or self distribution

@dharma-guardian could add the process for safari

**Comment by dharma-guardian** [comment]
To publish to the Safari Extension Gallery you need an Apple Developer Account which is 99€ annually. So far my old free account works to create a bundle and we had no problems in Safari. So, I suggest skipping Safari for now. I might buy a license myself, because I develop for iOS, so a temporary solution would be to use my account.

**Comment by dharma-guardian** [comment]
https://developer.apple.com/safari/resources/

**Comment by apoller** [comment]
We also have guys inhouse with Apple developer accounts afaik

**Comment by dharma-guardian** [comment]
Testing Yirans version showed, that in windows systems ROSE is still dissabled after a few hours/ a day.

**Comment by apoller** [comment]
Done for Chrome Webstore

**Comment by dharma-guardian** [comment]
As we are not planning a RC for Firefox I move this to ROSE 3.1.

**Comment by dharma-guardian** [comment]
Ok, close it because we have to reconsider deploying for Firefox first.
