### ISSUE TITLE
Process on reset including deletion of data

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#133]
Create a button under Data Management

**Comment by iamolivinius** [comment]
Need more information:

What is meant by reset? Deleting (which) data? Reset install date as well? Wipe complete storage? wipe config, too?

**Comment by dharma-guardian** [comment]
@apoller and I concluded that we need two options:
1. "Reset Configuration" removes all configurations to restart the configuration wizard, but not the tracked data (like activities, interactions, etc.)
2. "Delete All Tracking Data" removes all information Rose gathered (activity, interaction, etc.)

I think there is no reason to completely wipe the storage, nor removing install date.

**Comment by apoller** [comment]
I suggest that in case the wizard is restarted via the "Settings page", the tracked data are not to change, but only the ROSE configuration is erased and the user has to provide a new configuration file or switch to the default configuration.

However, there should be a possibility "to wipe ROSE". To this end we can build a button in the data management dialogue, opening a modal dialogue for confirmation ("Are you sure?") and then to wipe all data. The question is whether it makes sense at this point to also wipe the configuration?

**Comment by iamolivinius** [comment]
I'm going with Felix's proposal, OK?!

**Comment by apoller** [comment]
Yes that's okay. Go ahead

**Comment by dharma-guardian** [comment]
When resting configurations, we still need to activly remove all networks, observers and extractors.

**Comment by iamolivinius** [comment]
Well, this wasn't mentioned before. I'll add this soon
