### ISSUE TITLE
Sidebar: ui improvements

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#135]
* [x] smaller textareas
* [x] button at bottom,
* [x] labeled rating (low/high)

**Comment by dharma-guardian** [comment]
Text-Labels prove difficult. Something like that maybe: 
![bildschirmfoto vom 2015-07-28 12 34 29](https://cloud.githubusercontent.com/assets/1899308/8929360/2f9aa306-3525-11e5-8175-3c47978ed92e.png)

**Comment by iamolivinius** [comment]
LGTM

**Comment by dharma-guardian** [comment]
#141
