### ISSUE TITLE
Buttons in RoseUI Settings to manually start updating observers/extractors

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#139]
In Ember / settings tab sendMessage to background script to start update process

**Comment by dharma-guardian** [comment]
Give feedback about version/time since last update

**Comment by iamolivinius** [comment]
More information needed:

"updater interval" scale: hours, days, weeks, month, all of it?
"version/time since last update": be more precise about that. last-run or similar information are not available

**Comment by dharma-guardian** [comment]
- mh updater interval maybe a dropdown with hourly, daily, weekly, monthly? What makes sense in a period of a study? 
- there is a timestamp in the storage from configuration and a timestamp in the repository

**Comment by iamolivinius** [comment]
Guess I'm not able to find the timestamp in the storage. Can you link it here? 

Should both information be visible? repository timestamp and "last run of the updater" timestamp?

**Comment by dharma-guardian** [comment]
It's in the SystemConfigurations.

**Comment by iamolivinius** [comment]
I see. Could be semantically a bit more meaningful i.e. `updaterLastRun`

**Comment by iamolivinius** [comment]
"Updater Interval": should this be set in the settings menu and/or studyCreator

**Comment by dharma-guardian** [comment]
Just added current timestamp to config after update in ae39de2c230ca4f9b90b40dc147c76773a336f04.
How do we push this to ROSE UI or show some kind of feedback, respectively.
We could trigger a loading animation until a message is received and maybe we add a little result text?
