### ISSUE TITLE
ROSE customized version survey wording updates

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#141]
Here are the updated versions of the wordings of the surveys and comment side bar questionnaire:

![image](https://cloud.githubusercontent.com/assets/3218051/8936483/775cb4c2-3507-11e5-868d-31e801418b51.png)

![image](https://cloud.githubusercontent.com/assets/3218051/8936491/7f9b243e-3507-11e5-9e36-e7655903b2b2.png)

- [x] sidebar
- [x] survey 1
- [x] survey 2

**Comment by dharma-guardian** [comment]
#103

**Comment by YiranWangPARC14** [comment]
Here are two updates on the wording of the surveys:

In Comment sidebar diaries:
Q2. remove the option "Event page"
Q3. change "Is this the first time you hear about this topic" into "Is this post about a topic that you have already been interested in?"

**Comment by dharma-guardian** [comment]
#113

**Comment by dharma-guardian** [comment]
For now the functionality is implemented. For any errors please open new tickets.
