### ISSUE TITLE
Export/Backup needs meta data of the format

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#143]
from RoseV2
```JSON
{
    "install-date": "2013-06-04T19:08:30.057Z",
    "export-date": "2013-06-20T14:02:08.833Z",
    "rose-data-version": 1.2
}
```

**Comment by dharma-guardian** [comment]
I think Rose-Data has it's own versioning. So, it rather would be 1.3, so a minor jumo from 1.2? We have to compare the changes I guess.

**Comment by iamolivinius** [comment]
Well, then lets make it a 1.3. As long as we do not add a semantic to major, minor, etc. this is seems to be more or less random to me.

**Comment by apoller** [comment]
The semantics is as follows: 

+ change in major version if backwards compatibility is broken
+ change in minor version if data fields added only, but format still backwards compatible within the same major version

So I think 1.3 should be appropriate, isn't it?

**Comment by dharma-guardian** [comment]
I'm going to check this.

**Comment by iamolivinius** [comment]
Checked it! Breakes backwards compatibility. So it's a `2.0`
