### ISSUE TITLE
Suggestions for the wording of the instructions (beta3)

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#144]
![image](https://cloud.githubusercontent.com/assets/3218051/8966149/9275dad0-35e4-11e5-83d3-330fabec8c57.png)

**Comment by YiranWangPARC14** [comment]
Do you also want me to go over the HELP page? Would it be easier if I send a word document with tracked changes?

**Comment by dharma-guardian** [comment]
Because, this an image again, a text version would be nice. I would really like to know why this is happening. Did you try to copy & paste it, with `cmd + c` and `cmd + v`?

**Comment by YiranWangPARC14** [comment]
I just copied and pasted from a word document.. It looks like github
automatically transfers the text into an image somehow?

Here is the text version:

Here are my suggestions on the wording of the instructions. A. is the
current wording in the released beta3. B. is the alternative wording I
recommend.


On the “Interactions” page:

A. “All your recent interactions *for* this social media page recorded by
ROSE.”

B. “All your recent interactions *on* this social media page recorded by
ROSE.”



On the “Data Management” page:

A. “Here you can review and download all data recorded and collected by
ROSE. If you press the "Download" button you can store all data in a file
locally on your computer.”

B. “Here you can review and download all data recorded by ROSE. If you want
to store the logs in a local file on your computer, press the "Download"
button.”





On the “Settings” page:

1.     Under Language

A. “Choose your preferred language. ROSE can also adopt the browser
language ("auto detect" option).”

B. “Choose your preferred language, or use the default language from the
browser ("auto detect" option).”



2.     Under Comment reminder

A. “ROSE can ocassionally display reminders to remind you to comment on
your actions if that is required by the study you are participating in. You
can deactivate this features if it disturbs you.”

B. “If the research study requires you to comment on your activities, ROSE
will occasionally display a message to remind you to do so, if the feature
is activated. You can deactivate this feature if it disturbs you.”



3.     Under “features for researchers and developers”

A.“ROSE has additional features for field researchers and ROSE developers.
These features are normally not visible, but can be activated here.”

B.“ROSE provides additional features for field researchers and ROSE
developers. You can activate these features here to make them visible.”

**Comment by apoller** [comment]
Yiran's proposals sound all reasonable to me. Will implement them for the next build.

Regarding the text to image conversion: when you drop the text in the text area at the ticket page, does it already turn to an image? In that case the browser might be the cause of these troubles.

**Comment by YiranWangPARC14** [comment]
Andreas,

Sorry I browsed past this email - when I paste the text in the area, it
converts the text into an image. I don't see the image in the text box, I
only see a link to an image. When I submit my content, then I see the
image. I thought it might be a github thing. Next time I'll try Safari to
see if that's still the case.

Yiran

**Comment by apoller** [comment]
The "help" pages need a content-wise revision hence proof reading is not reasonable yet. @YiranWangPARC14 I will let you know when you can check the "help" pages

**Comment by YiranWangPARC14** [comment]
Got it. Thanks!

Yiran
