### ISSUE TITLE
Sorting and Grouping in Comments/Interactions

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#145]
After some time the list is getting a bit long. Maybe the list should be grouped by days/weeks?

**Comment by iamolivinius** [comment]
Pagination and grouping are two different things.
In my opinion pagination is a bad thing, grouping interactions and comments
per day or so is the better way to go.
Am 30.07.2015 6:57 nachm. schrieb "Felix" <notifications@github.com>:

**Comment by dharma-guardian** [comment]
Yeah, I would prefer grouping. We have to make it managable in some way. 

And I think the ordering should start with the most recent interaction on top. Right now it is vice versa.

**Comment by iamolivinius** [comment]
This means we want sorting and grouping features.
Am 30.07.2015 7:04 nachm. schrieb "Felix" <notifications@github.com>:

**Comment by dharma-guardian** [comment]
We implemented pagination in #220
