### ISSUE TITLE
Decouple semantic css style from network via different namespace

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#147]
We could compile our own version of semantic ui with a unique class identifier.

**Comment by iamolivinius** [comment]
Why should we?

**Comment by dharma-guardian** [comment]
http://stackoverflow.com/questions/31903494/how-to-namespace-or-prefix-semantic-ui
Impossibru
![Impossibru](https://media.giphy.com/media/GeFmrJ2paxilG/giphy.gif)
