### ISSUE TITLE
Q2 and Q3 comment side bar value not shown in RoseUI (beta5)

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#152]
The answers to the two radio button questions: "You are currently viewing" and "Is this post about a topic..." from the comment side bar are not shown in the RoseUI.

**Comment by dharma-guardian** [comment]
Actually thery are stored, but not shown in RoseUI. You can see it in the database or by reopening a previous comment again. The boxes should be ticked then.

<img width="327" alt="bildschirmfoto 2015-08-05 um 20 36 53" src="https://cloud.githubusercontent.com/assets/1899308/9094386/c5124028-3bb1-11e5-9bf1-f394b81e8046.png">

**Comment by dharma-guardian** [comment]
@iamolivinius can add these to the RoseUI.

**Comment by YiranWangPARC14** [comment]
Got it. Thanks!
