### ISSUE TITLE
Activity Trackers loose a lot data ?

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#154]
I don't know how much this affects the activity tracking, ~~but while navigating through facebook, the page and therefore the content script is reloaded. All activity which is not yet stored, is lost then.~~
I experienced no click-activities.
Maybe smaller intervals?

**Comment by iamolivinius** [comment]
AFAIK navigation in facebook does not trigger the content-script to reload. If this would be the case you'd see "integrated x observers" log messages each time you'd click a facebook link.

**Comment by dharma-guardian** [comment]
jep, forgot that, but had no click-activities showing up for some time. still wonders me

**Comment by dharma-guardian** [comment]
I use the activity data in the engage tracker and it seems fine with just a smaller store interval. So that's it for me.
