### ISSUE TITLE
Possible storage leak

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#155]
In the past 5 days of testing the custom build, I noticed that occasionally the interactions were not recorded. 

For example, I have noticed that some "likes" and "shares" were not recorded. First I thought that the observer might have been broken. But later on (sometimes even without re-starting the browser), the interactions of the same kind were recorded. So it is possible that there is a storage leak.

**Comment by dharma-guardian** [comment]
Closed in favor of #156
