### ISSUE TITLE
Survey 2 triggers unexpectedly when locked out

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#163]
The condition is triggered, because not logged in, but even with active fb before.

**Comment by YiranWangPARC14** [comment]
Survey 2 triggers unexpectedly. I was on FB logging page, S1 triggered correctly, which I dismissed. A few seconds after, survey 2 was triggered. I didn't had a chance to log in.
<img width="1087" alt="scnshot s2" src="https://cloud.githubusercontent.com/assets/3218051/9739918/d94cae42-5606-11e5-8d88-5d3c6adc4ea6.png">

**Comment by dharma-guardian** [comment]
Jep, that is the error I found before. I miss to track wether the user was online before, that's all.

**Comment by dharma-guardian** [comment]
I close it for now.
