### ISSUE TITLE
survey 1 ratings offset (Yiran build 4.0)

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#167]
There seems to be an offset of the three rating questions in survey 1. When I rated all 10s, the answers recorded in the Comment logs were all 9s.

**Comment by YiranWangPARC14** [comment]
It seems like only ratings of '10' is recorded wrong. Tried another survey 1, input '1' ,'5', '10', recorded '1' , '5', '9'.

**Comment by YiranWangPARC14** [comment]
Tried another survey 1, input '9', '10', '8', recorded '8', '9', '7'.

**Comment by iamolivinius** [comment]
Computer Scientists start counting at 0 :wink: 

But your second comment could indicate a bug

**Comment by YiranWangPARC14** [comment]
It started from 8. ratings of 1-7 was recorded correctly. Check 8,9,10 only.

**Comment by dharma-guardian** [comment]
@YiranWangPARC14 I implemented it with 9 stars, so there can not be a value of 10. Can you try it again?

**Comment by YiranWangPARC14** [comment]
HA! I see! My bad!! For some reason I kept thinking the last one is 10, so I always count backwards... So there is no issue - the ratings are from 1 - 9.

**Comment by dharma-guardian** [comment]
That's what I guessed. :)
