### ISSUE TITLE
Add Type to comments

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#170]

**Comment by iamolivinius** [comment]
engaged: string

**Comment by dharma-guardian** [comment]
Have you changed this in facebook.ui and survey as well?

**Comment by iamolivinius** [comment]
u need to change the value that should be saved

**Comment by dharma-guardian** [comment]
![Forever](https://m.popkey.co/3e31ee/gr7bO.gif?c=desktop&l=search&f=.gif)
