### ISSUE TITLE
Generalize Activity Trackers for other networks or create extractors

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#171]
include into RC?

**Comment by apoller** [comment]
Is already somewhat generalized, but in ROSE data it shall be recorded on which page the activity was recorded.

**Comment by dharma-guardian** [comment]
@iamolivinius Can you have a look at the windowTrackerClass branch? You async construction seems not to work with class methods and I don't want fiddle too much with it.

**Comment by dharma-guardian** [comment]
@iamolivinius Already solved it.
