### ISSUE TITLE
Later responses override earlier responses when there are multiple disengagement surveys

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#173]
I have observed something interesting and I wonder if this is done intentionally from your end:

There were 3 disengage surveys (survey 2) piled up in my browser, because I didn't do any of them when they were first triggered nor dismissed them.

When I clicked on the first survey 2 (the one that was triggered the earliest), and input the ratings '1', '1', '1', I refreshed the ROSE interface and confirmed that the responses were recorded in "Comments", with a time stamp (6:04pm). I then clicked on another survey 2 that was on the browser tab, input ratings '4', '4', '4'; I then refreshed the ROSE interface, and found that the previous responses  ('1', '1', '1') where gone, only the '4', '4', '4' were recorded (with the time stamp 6:04pm). I don't know if the second response override the first one, or the first one got lost, as I did these two surveys within a minute.

I was wondering if this is an intentional choice, that is, when there are multiple open survey 2's, only record the last response? If so, I think that makes sense.

**Comment by dharma-guardian** [comment]
It is not intentional, I will have a look into it.

**Comment by YiranWangPARC14** [comment]
This problem is replicated for a few times now. Below is an example:

I completed two disengagement (S2) surveys and one engagement (S1) survey consecutively, probably within a few minutes of each other. Only the responses of the  last survey (S1) was recorded (with the time stamp of the last survey). The responses of early surveys was recorded temporarily when they were first submitted, only to be overridden by the later surveys.

I checked the logs from Data Management, I don't see a record the missing survey responses, so it is probably not a visualization problem from the Comment interface.

**Comment by YiranWangPARC14** [comment]
Hmm.. this issue is getting worse:

Now, even if I don't pile up multiple surveys, instead, I do each survey (S1 or S2) when they were first triggered, the later ones still override the earlier ones.

**Comment by iamolivinius** [comment]
Looks like a lost-update problem to me. I guess in S1 a comments collection is loaded during initialization. These collection does not have access to the S2 data set and could overwrite the S2 changes when saved.

**Comment by dharma-guardian** [comment]
Not tested it, but I hope this should fix it.

**Comment by YiranWangPARC14** [comment]
Is this a new release?

**Comment by dharma-guardian** [comment]
I wanted to wait for the wordings from Andreas and the fix for the updater by Oliver, but I just created a new release for you.

**Comment by YiranWangPARC14** [comment]
Ok thanks Felix!! Let me test it. Please let me know when the new one replaces this version.

**Comment by dharma-guardian** [comment]
Version 5 is online. Just download it from the releases.

Am 09.10.2015 10:13 nachm. schrieb Yiran Wang <notifications@github.com>:
Ok thanks Felix!! Let me test it. Please let me know when the new one replaces this version.

**Comment by YiranWangPARC14** [comment]
Awesome! Thanks everyone!
