### ISSUE TITLE
friend-request-add Observer is broken

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#177]
When viewing a facebook profile and clicking friend request, it shows your lists and this is click then is not recorded by ROSE.

**Comment by dharma-guardian** [comment]
`.FlyoutFriendMenu li.FriendListItem a, .FlyoutFriendMenu li.FriendListItem a > span`

**Comment by dharma-guardian** [comment]
I cannot reproduce this bug anymore, maybe the change was reverted.

**Comment by YiranWangPARC14** [comment]
It is working fine now on my side too.
