### ISSUE TITLE
Store log message in Appplication DB and show them in debug screen

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#179]
Use the/a log module to give debug information (e.g. current configuration) without requiring to use developer tools.

- [x] log module writes to storage
- [ ] include log into ROSE where applicable
- [x] a simple debug view in ROSE-UI under Researcher Features that prints out the logs and configs/settings

**Comment by iamolivinius** [comment]
How should a log message document look like? 

My suggestion: 

```json
{
    "date": 1445949095053,
    "message": "I'm a freaking log message",
    "origin": "content or background"
}
```

But no idea right now how to get the origin of a message.

**Comment by dharma-guardian** [comment]
Do you think we need structured records? So far, we generate this string: https://github.com/secure-software-engineering/rose/blob/master/app/rose/log.js#L56
Maybe one record with the line by line text log would suffice?

**Comment by iamolivinius** [comment]
I'd recommend to rely on more primitive values and not just on the preformatted string. For example if u want to internationalize date formats presented to a user.

**Comment by dharma-guardian** [comment]
I know of the advantages, but I ask, if we need it. In my opinion Internationalization for example is not necessary.

**Comment by iamolivinius** [comment]
Well, what would be the disadvantages? If there are none, I'd choose advantages over disadvantages :wink:

**Comment by dharma-guardian** [comment]
More to implement?

**Comment by iamolivinius** [comment]
See: https://github.com/secure-software-engineering/rose/commit/9fcf2f39a14b2ff6be60f508716b57cc7a644bb3

**Comment by iamolivinius** [comment]
How should this "simple debug view" titled?

 - event viewer
 - debug log
 - etc. 
 - pp.

**Comment by dharma-guardian** [comment]
pp. sounds nice ;)
My proposal: Debug Log
Another option would be: Console/Konsole
