### ISSUE TITLE
Study creator: repository fetch broken. oh nooooooo 

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#180]
![oh no!](https://media.giphy.com/media/7QxZfWnBLdGI8/giphy.gif)

The following values result in errors:

```
https://secure-software-engineering.github.io/rose/example/base.json
https://secure-software-engineering.github.io/rose/example/
https://secure-software-engineering.github.io/rose/example
```

![bildschirmfoto vom 2015-10-20 19 53 15](https://cloud.githubusercontent.com/assets/1899308/10616201/4071124c-7764-11e5-861c-5ebe9607e596.png)

And which URL should we use. Maybe the full url with filename again and all filenames in the base.json should be absolute URLs, not relative.

**Comment by iamolivinius** [comment]
"Convention over configuration" vs. explicit configuration?

**Comment by iamolivinius** [comment]
And BTW. It's not broken, it's "verbose". I'll leave this open to discuss the schema that should be used for the repository URL

**Comment by dharma-guardian** [comment]
Ok, if it is not broken, how can I produce a state of a list of the Observers then. I cannot get it work right now.

Any suggestions according the schema?

Am 21.10.2015 3:09 nachm. schrieb Oliver Hoffmann <notifications@github.com>:

And BTW. It's not broken, it's "verbose". I'll leave this open to discuss the schema that should be used for the repository URL

**Comment by iamolivinius** [comment]
http://secure-software-engineering.github.io/rose/example/
https://secure-software-engineering.github.io/rose/example/

Works for me

**Comment by dharma-guardian** [comment]
It's working again on my side. Maybe I was in a temporary broken state.

My proposal for the schema would be to use full URLs at all times. That would leave the format more open and stable, because it would not enforce a certain logic, how these relative paths relate to each other.

**Comment by apoller** [comment]
@dharma-guardian Problem is that in this case nobody can mirror our repository.
