### ISSUE TITLE
English UI wording updates

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#182]
Here is the updated wording for all the pages in the English UI. See attached Word document.

In this document, I included screenshots of the current wording, and the the updated wording below. Many sentences were re-written, and there are also some alterations in the paragraph structure, to cater to English speakers. 

Let me know if there are questions. Or if you need me to plug these changes in the corresponding wording file in the source code.

[ROSE 6.0 wording yw.docx](https://github.com/secure-software-engineering/rose/files/21354/ROSE.6.0.wording.yw.docx)

**Comment by iamolivinius** [comment]
:+1: Looks good to me

**Comment by dharma-guardian** [comment]
@YiranWangPARC14  There a few missing, but nothing critical:
- [ ] Modal dialogs, when clearing all data or resetting Rose (I guess you were scared clicking it ;)
- [ ] Study Creator (has to be activated under settings > researcher and developer features)
