### ISSUE TITLE
Minor errors and improvements to highcharts viz

### ISSUE THREAD

**Issue by eppfel** [secure-software-engineering/rose#184]
- [ ] I cannot make sense of the login status chart. Is this due to the data?
- [ ] The scale in the window and login status chart are nominal and should be change accordingly.
- [ ] I like the graphs, but with some charts e.g. window activity a zoom level smaller than one month would be helpful. I zoomed in by hand and only then you can actually see some behavior patterns.
- [ ] The y-Axis of the login status chart is falsely named `distance in pixels`
- [ ] There should be either a dropdown control box in the dashboard to select the website shown, or different colors should be used in the diagrams

**Comment by iamolivinius** [comment]
I need some improvement proposals - at least for point 3.

**Comment by dharma-guardian** [comment]
Point 2: Maybe use something similar to Ivy: like a timeline with marks at logged-in states.  
Point 3: the y-axis should be named with labels instead of numbers (or at least explained on the axis label)
