### ISSUE TITLE
Include custom bundle/modules of crypto.js via npm

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#185]
Currently we include digitalbazaar/forge through `bower` and create a bundled version during the `npm install`.
The disadvantages:
* it has to be loaded as a separate file, although it is used only in particular situations
* it bloats the install process
* the package is pretty big ~250kB, but the modules we need are only ~45kB

I tried two options without success:
First i tried to include node-forge via npm, but currently it does not support browserfy and there is no easy workaround: digitalbazaar/forge#294 and digitalbazaar/forge#126
Then I at least tried two create a smaller bundle as explained here: digitalbazaar/forge#156
Changing ./minify.js like that:
```JS
  include: ['js/md'],
```
But the content script fails with the following error:
```
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: Error: No js/forge
    at Object.kango.lang.evalInSandbox (chrome-extension://kcpjjkfllehglljdbpmfjdljnllkddkn/includes/content.js:8:1910)
    at Object.kango.lang.evalScriptsInSandbox (chrome-extension://kcpjjkfllehglljdbpmfjdljnllkddkn/includes/content.js:8:2087)
    at chrome-extension://kcpjjkfllehglljdbpmfjdljnllkddkn/includes/content.js:17:197
    at Object.exports.object.forEach (chrome-extension://kcpjjkfllehglljdbpmfjdljnllkddkn/includes/content.js:4:3983)
    at chrome-extension://kcpjjkfllehglljdbpmfjdljnllkddkn/includes/content.js:17:162handler @ extensions::uncaught_exception_handler:8
```
I wanted to track my progress here and propose we wait until they support browserify.

**Comment by iamolivinius** [comment]
Yeah.... that's not gonna happen any time soon, if at all

**Comment by iamolivinius** [comment]
Close this if you're ok with that: https://github.com/secure-software-engineering/rose/pull/186
