### ISSUE TITLE
Observer for event interactions broken

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#187]
Due to layout changes on fb no interactions are registered, bug was reported by @YiranWangPARC14 and I confirm it.

- [ ] confirm event: button / menu option after interest
- [ ] ~~maybe~~ interested in event: button, menu option after confirm
- ~~[ ] decline: menu option after confirm~~
- ~~[ ] not interested: menu option after interested~~
- [ ] unwatch counts for not interested and not going

at the following positions: single event page, post on timeline/profile/site, under events (calendar)

- [ ] create event is functional, except for the the button under the events tab personal profile

**Comment by YiranWangPARC14** [comment]
If the event page uses the old options (Going, Maybe, Can't go), the interactions are still recorded correctly now.

If the event page uses the new options (Interested, Going, Ignore), then the interactions are not recorded.

I have not created a new event myself, but I have received event invites, some of which used the old options, some of which used the new options. I suspect that FB is rolling in the new options while still keeping the old options for now.

**Comment by dharma-guardian** [comment]
@YiranWangPARC14 Good to know. I will add the new observer patterns and leave the old ones, so we can track both.
