### ISSUE TITLE
ROSE Yiran 7.0 testing notes

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#189]
A few higher level questions:

~~1. For Yiran’s version, is it possible to remove or hide the Reset function in the Data Management from the UI?~~
2. Now the red comment ribbons are in the timeline and personal profile. Is there a way to add in comment ribbons to posts in FB groups?
3. Can you cut a Safari version for 7.0?
4. For windows, ROSE seemed to disable itself automatically. It seems like we need to put it on Google Web Store. Is that a possibility?

More detailed feedback, suggestions to change, or survey wording that is still in discussion:

5.Pre-FB survey:
5.1.	Add a title: Pre-Facebook Survey
5.2.	[in discussion] Please rate the following scales based on *how you feel right at this moment* -> *how you felt in the last thing you did, right before you came to Facebook*.
Concentration *- How well were you concentrating?*
Interest *- Did you find the activity interesting?*
Enjoyment *- Did you enjoy what you were doing?*

6.Post-FB survey:
6.1.	*Rose Survey: Disengage Facebook* -> *Post-Facebook Survey*
6.2. [in discussion] *Dismiss for now* -> *I am not leaving Facebook yet*
6.3.	*Please rate the following statements using the following scale (1 = Strongly disagree, 5 = Strongly agree), which reflects based on your experience on Facebook JUST NOW.*
->
*Please rate the following statements based on your experience on Facebook JUST NOW. (1 = Strongly disagree, 5 = Strongly agree)*

It seems I *am* -> *was* ‘running on automatic’ when using Facebook, without much awareness of what I *am* -> *was* doing.

I *rush* -> *rushed* through activities (e.g., *liking*, posting status updates, commenting, ~~launching apps,~~ joining groups) on Facebook without being really attentive to them.

~~I quickly check updates from Facebook without being aware that I am using it.~~

7.Comment sidebar (the red ribbon)
7.1 On the FB UI, it turned out that the word "comment" was confusing to a few participants. They thought they can actually comment on Facebook using that function, even though I explained to them it was really a diary function. So I was wondering if it is possible to change the "comment" in the red ribbon into "Note" or "Diary". I think diary is a better word, but in the ROSE interface, there is also a function called "Diary", so using the same name could again be confusing. This Diary function is not used, so I wonder if it is possible to remove or hide it from this version of ROSE.

7.2 Similarly, on the ROSE UI, "Comments" were sometimes mistakenly understood as the actual comments made in Facebook. Can we change that word into the word we end up choosing for 7.1 (either Notes, or Diaries?)

7.3 In the side bar, add a title before the first question, "My Notes" or "My Diary" (again, depend on which word we choose for 7.1 and 7.2)

7.4 In the side bar, add a line of text after the last question and right before "Dismiss for now Done" button: "Please take a screenshot of the post".

7.5 [in discussion] In the side bar, last question, *What made you decide to read this post?* -> *What drew your attention to this post and What is your reaction to the post?*

**Comment by iamolivinius** [comment]
1. Yes, but this would bein contradiction to roses basic principle that the users should be in charge over their data

2. Yes

3. @dharma-guardian 

4. You're right. We talked about the different app stores but I'm not sure what's the status quo on this topic. @apoller

**Comment by apoller** [comment]
4. Status is that I have a Chrome Web Store Developer Account and paid the $5 fee. So I can upload apps to this account.
