### ISSUE TITLE
Comment Ribbons in FB groups

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#190]

**Comment by dharma-guardian** [comment]
Works only on reload now. Have to further look into it.

**Comment by YiranWangPARC14** [comment]
In the ROSE version uploaded in the google Chrome store, I don't see the comment ribbon in FB groups. Double check that? Thanks!

**Comment by dharma-guardian** [comment]
Fixed it with the commit. Will be in the next release.

**Comment by YiranWangPARC14** [comment]
Thanks!

On Tue, Dec 15, 2015 at 1:36 PM, Felix <notifications@github.com> wrote:

> Fixed it with the commit. Will be in the next release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/secure-software-engineering/rose/issues/190#issuecomment-164904829>
> .
>



-- 
Best,
Yiran
