### ISSUE TITLE
Naming of Rose Versions with actual Rosa species

### ISSUE THREAD

**Issue by eppfel** [secure-software-engineering/rose#198]
I think this would be a nice addition. I propose new names for major and minor versions (like Google Android) and maybe even special releases like Yiran's.
https://en.wikipedia.org/wiki/List_of_Rosa_species

For 3.0 my recommendation would be [Rose gallica](https://en.wikipedia.org/wiki/Rosa_gallica)

**Comment by dharma-guardian** [comment]
Andreas suggested: ROSE Vanilla ^^
![Vanilla Rose on flickr](https://farm1.staticflickr.com/49/149675265_3300204d54_o_d.jpg)
