### ISSUE TITLE
Add different keys for infoText in the rating for sidebarcomment and engage survey

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#203]
The 3 rating questions in the engage survey and the comment sidebar seem to be using the same elements in the "sidebar" object. If I want to ask the question slightly differently (for the "inforText") in these two places, is there a way to do it?

**Comment by YiranWangPARC14** [comment]
This is for sidebarComment and *engage* survey, not the disengage survey.

**Comment by dharma-guardian** [comment]
Sure, just a typo. Thx
