### ISSUE TITLE
add a question in the engage survey

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#207]
Add a multiple choice question before the 3 rating questions:

Question: What was the last thing you did right before you came to Facebook?
Options: Schoolwork offline, Schoolwork on the computer, Non-work activities on the computer, Non-work activities offline, Not doing anything in particular

**Comment by dharma-guardian** [comment]
Finally fixed in these:
7e91fd9423b2730ed828d9c38daba2fb1bb30121
99de8fe2cfb3d071825ad6db5d3ec18aebe8c9f8
94f5abb52b5480f51fe2ac105478c619496185d2
