### ISSUE TITLE
More verbose updater and visual feedback

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#210]
Right now there is no way to see, if an update was processed, besides looking into the storage. The following should be added:

 - [x] show visual feedback as long as the update is processed (loading gif, etc.) (optional) 
 - [x] write stats about update in to debug log (was something updated, or not? what/how much?)
 - [x] show visual feedback of success / update last update timestamp in ui. see #209

**Comment by dharma-guardian** [comment]
@apoller update itself seems to be working.

**Comment by dharma-guardian** [comment]
The timestamp is not updated in the UI right now.
Actually we discussed there should be 
* [ ] one info about when the update was last executed -> time the last manual/auto update
* [ ] one info from when the current repository version is -> timestamp in the repo

**Comment by iamolivinius** [comment]
Right now I show lastUpdated and lastChecked dates. 

I also don't see the point in the timestamp value inside the base.json file any more. base.json is the file with the least moving parts in it but needs to be updated every single time you make changes to another file. 

@apoller can we close this?

**Comment by dharma-guardian** [comment]
![bildschirmfoto vom 2016-04-08 18 14 12](https://cloud.githubusercontent.com/assets/1899308/14386415/f5357b34-fda4-11e5-8878-74c4a72e05d8.png)

That's how it looks now. @apoller Is this sufficient? Then close the ticket.
