### ISSUE TITLE
Add pagination for Application Log / Debug Log

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#211]
The log can become pretty long and therefore Chrome is not responding for some seconds.

Another option would be to render the complete log as one text in an textarea field.

**Comment by dharma-guardian** [comment]
Because it is basically a developer feature, @apoller and I decided that an large textarea with just a text is quite sufficient.

**Comment by iamolivinius** [comment]
Did you do some performance profiling to back your conclusion?

**Comment by dharma-guardian** [comment]
Nope.

**Comment by dharma-guardian** [comment]
Here you go:
above 730MB of RAM and unresponsive tab for about 1min **with pagination**.
<img width="1399" alt="bildschirmfoto 2016-01-12 um 15 11 38" src="https://cloud.githubusercontent.com/assets/1899308/12265734/2b78561c-b93f-11e5-8f51-0ec781ab75ec.png">

[CPU Profile Download](http://cloud.felixepp.de/index.php/s/9vUYcEz5W5LjtLf)

**Comment by dharma-guardian** [comment]
Why not our proposal?

**Comment by dharma-guardian** [comment]
The application log has 176388 entries on my side, which is too much. I will improve the logging, but the issue remains.

**Comment by dharma-guardian** [comment]
This is how it looks on SITbuntu with 16673 entries:
![bildschirmfoto vom 2016-01-12 16 37 31](https://cloud.githubusercontent.com/assets/1899308/12267942/dce6c482-b94a-11e5-8c81-623cba317da0.png)
Not as bad. We might limit the maximum amount of logs or the time.
