### ISSUE TITLE
Text styling issues for engage and sidebar

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#212]
In sidebar (study notes), currently, all text in Q1,Q3,Q4 appears bold. Only text "right after" in Q2 should be bold, unbold the other text?

In engage survey, all text in Q1 appears bold. Unbold it?

Thanks!

**Comment by dharma-guardian** [comment]
![bildschirmfoto vom 2016-01-12 15 59 56](https://cloud.githubusercontent.com/assets/1899308/12266837/8817b86c-b945-11e5-81dd-ced42405fe95.png)
This is the default of the ui framework we use. You want everythung besides "right after you read the post" not bold, right?

**Comment by YiranWangPARC14** [comment]
Yes, if it is a simple fix. If it is not, I can live with it because I'm sure there are more important issues to solve. Here is what I saw in my browser:

<img width="342" alt="screen shot 2016-01-12 at 8 48 01 am" src="https://cloud.githubusercontent.com/assets/3218051/12270105/539f6da0-b909-11e5-99a2-e69567d94f87.png">
<img width="344" alt="screen shot 2016-01-12 at 8 48 13 am" src="https://cloud.githubusercontent.com/assets/3218051/12270104/539aeba4-b909-11e5-8c38-a52e448fc283.png">
