### ISSUE TITLE
Delete stale branches (Except rose-v2)

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#215]
Check stale branches for unmerged stuff and if it is important / has to be archived. Then delete them to clean up the repository.
@iamolivinius I checked them and think they can be deleted without aftermath, but I wanted you to reassure.

**Comment by iamolivinius** [comment]
you could delete all unnecessary branches. i'd leave kramm and kocksch branches in place.

**Comment by dharma-guardian** [comment]
Does this mean, all stale branches besides kramm and kocksch can be deleted. Because promise updater has an open pull request.

**Comment by iamolivinius** [comment]
I'll check it again but I think this is an old version of what I already
committed.

**Comment by iamolivinius** [comment]
done
