### ISSUE TITLE
Although stored, Interactions are missing in ROSE UI

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#216]
I experienced this when experimenting with a reddit configuration. #214 
The observers are successfully tracking the interactions, but they are not shown in the UI. Checking the storage, turns out everything is correct, so it seems to get lost during render. It is a consistent bug. a reload does not change the outcome.

I have not yet checked wether this happens with facebook too, or not.

Here is an example with the second interaction (view-link at 21:39) is missing:
Log:
```
Navigated to https://www.reddit.com/
[ROSE, module: ObserverEngine, time: 07.01.2016 22:36:52] Integrated 6 observers
[ROSE, module: ObserverEngine, time: 07.01.2016 22:38:28] New interaction: {"createdAt":"2016-01-07T21:38:28.701Z","origin":{"observer":"upvote-link","network":"reddit","version":"0.1","target":{"authorId":"638f4","contentId":"7d8b8"}}}
[ROSE, module: ObserverEngine, time: 07.01.2016 22:39:23] New interaction: {"createdAt":"2016-01-07T21:39:23.006Z","origin":{"observer":"view-link","network":"reddit","version":"0.1","target":{"authorId":"46f96","contentId":"e7e76"}}}
Navigated to https://www.youtube.com/watch?v=LYmY2tBYins
Navigated to https://www.youtube.com/watch?v=LYmY2tBYins
Navigated to https://www.youtube.com/watch?v=LYmY2tBYins
Navigated to https://www.reddit.com/
[ROSE, module: ObserverEngine, time: 07.01.2016 22:41:07] Integrated 6 observers
[ROSE, module: ObserverEngine, time: 07.01.2016 22:41:18] New interaction: {"createdAt":"2016-01-07T21:41:18.117Z","origin":{"observer":"view-link","network":"reddit","version":"0.1","target":{"authorId":"fb55c","contentId":"a2f8d"}}}
```

UI:
<img width="411" alt="ROSE UI showing two interactions track on reddit" src="https://cloud.githubusercontent.com/assets/1899308/12183947/7da2818e-b592-11e5-8f8a-8962a23253c3.png">

Store:
<img width="531" alt="screen shot 2016-01-07 at 23 04 45" src="https://cloud.githubusercontent.com/assets/1899308/12184077/5da46874-b593-11e5-85ee-c47ae6b472a4.png">

**Comment by dharma-guardian** [comment]
The missing record is not present in the data export either.

**Comment by apoller** [comment]
If it is in the data base and is neither shown in the UI and the data export I guess the routine for retrieving the data from the database has the bug. Does not sound as this would be a synchronization problem. However, we need to get it fixed as soon as possible.

**Comment by iamolivinius** [comment]
Can't reproduce the bug, sorry. Please don't paste JSON objects as a picture. No one wants to type it out in his/her console for debugging purposes.

**Comment by dharma-guardian** [comment]
Sry, did not think about it. I will have another look into the data. Maybe it is related to experimenting with reddit.

**Comment by dharma-guardian** [comment]
So, https://github.com/secure-software-engineering/rose/issues/214#issuecomment-172930245 by @iamolivinius seems plausible.
Yet, I found that the interactions are stored, but seem to be missing in the "Interactions" Collection:
<img width="993" alt="screenshot ROSE storage interactions count" src="https://cloud.githubusercontent.com/assets/1899308/12511494/fad38a4c-c111-11e5-8742-acf60edaf94b.png">
442 Interactions in the storage, but only 370 in the Collection.
The collection seems to be fully represented in the ROSE UI, e.g. Reddit Interactions in the collection and in the UI are 48. So, the Problem seems to be with the integrity of the collection.

**Comment by dharma-guardian** [comment]
Good news everyone: This particular problem belongs to reddit. All the missing interactions in my storage are from reddit.

**Comment by dharma-guardian** [comment]
@iamolivinius's theory https://github.com/secure-software-engineering/rose/issues/214#issuecomment-172930245 could be right: Of all 72 ~~virgins~~ missing interactions only **one** is not related to a page transition (`upvote-link`). All other interactions are `view-link` or `view-comments`.

**Comment by dharma-guardian** [comment]
It's reproducible and not specific to external or internal pages.
Will look for options to fix it. It seems on facebook no interaction ROSE tracks is actually reloading the page and therefore triggering this issue. So, i consider not important for yiran's study.

**Comment by dharma-guardian** [comment]
That's how I extracted the data: https://gist.github.com/dharma-guardian/de8b5b614682232e518b
