### ISSUE TITLE
Status-update observer is not working

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#219]
I experienced this posting in a group. Will verify it further...

**Comment by YiranWangPARC14** [comment]
I did a status update and it was recorded. What do you mean by status update in a group? Do you mean writing a post?

**Comment by dharma-guardian** [comment]
Exactly.

**Comment by dharma-guardian** [comment]
It is working, when you are at the frontpage. In your personal timeline, someone else's timeline and in a group it is not tracked. looking into to it now.

**Comment by dharma-guardian** [comment]
Group posts still missing, but profiel psts and deletes are in.
[rose-configuration .json.txt](https://github.com/secure-software-engineering/rose/files/92112/rose-configuration.json.txt)

**Comment by YiranWangPARC14** [comment]
Another possible observer:

I very often share a post via chat message. I know other people do it too.
It is not currently recorded as either "share" or "chat". If this is not
too much trouble, can you look into that as well? Thanks very much!

On Fri, Jan 15, 2016 at 7:42 AM, Felix <notifications@github.com> wrote:

> Group posts still missing, but profiel psts and deletes are in.
> rose-configuration .json.txt
> <https://github.com/secure-software-engineering/rose/files/92112/rose-configuration.json.txt>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/secure-software-engineering/rose/issues/219#issuecomment-171995104>
> .
>



-- 
Best,
Yiran
