### ISSUE TITLE
User friendly wording for observers/extractors updates

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#223]
Tracking package?

**Comment by apoller** [comment]
I'm currently tending towards using the "package" term though I'm not sure what to put in front of it:

O&E package (observer and extractor package)
tracking package
pattern package
website package

**Comment by dharma-guardian** [comment]
Actually it is data about a networks. Maybe, Network package**s** ?

**Comment by dharma-guardian** [comment]
Or Network Tracking Packages?

**Comment by YiranWangPARC14** [comment]
Network tracking sounds like network in the hardware sense, not in the "social network" sense.

I would advocate for either tracking packages, or site tracking packages.
