### ISSUE TITLE
Verification error is not handled in Updater

### ISSUE THREAD

**Issue by eppfel** [secure-software-engineering/rose#224]
I wanted to test the current implementation of the updater with my updates to the repository.
I started from the state and configuration in b8d6f84efc69f83c616c0d04eba36cf4199cd9b3 and performed the following steps:
1. Manual update
2. Reset configuration
3. Configure ROSE with old configuration in `assets/reddit-configuration.json`
4. Auto-updated: changes, success!
5. Manually updated: no changes, succes!
6. Pushed unsigned files to the repository
7. Manual update: fails, success, but unhandled

This generates leads to the loading animation not stopping until refresh and the following log:

```
[{"name":"facebook","updatedExtractors":[],"updatedObservers":[]}]
[ROSE, module: Updater, time: 19.01.2016 19:14:53] [{"name":"facebook","updatedExtractors":[{"name":"status-update","network":"facebook","version":"0.3","fields":[{"name":"sharerId","selector":"a[data-hovercard^=\"/ajax/hovercard/\"]:has(img)","attr":"href","match":".+profile\\\\.php\\\\?id=\\\\d+(?=\\\\&)|.+(?=\\\\?)|.+","hash":true},{"name":"contentId","selector":"a:has(span.timestampContent)","match":".+(?=\\\\?)|.+","attr":"href","hash":true}],"isEnabled":true,"id":"04672d2d-b88c-a095-f0cb-25677e81abb8"}],"updatedObservers":[]}]
[ROSE, module: Updater, time: 19.01.2016 19:21:38] [{"name":"facebook","updatedExtractors":[],"updatedObservers":[]}]
Unhandled promise rejection Error: hash mismatch(…)
Unhandled promise rejection Error: hash mismatch(…)
Unhandled promise rejection Error: hash mismatch(…)
Unhandled promise rejection Error: hash mismatch(…)
```

**Comment by apoller** [comment]
related to #208

**Comment by dharma-guardian** [comment]
Auto-update without internet connection throws an uncaught error as well. Still could be reasonable, but is related and at least should be considered catching/reflecting on the ui.
```
GET https://secure-software-engineering.github.io/rose/example/base.json net::ERR_INTERNET_DISCONNECTED
Uncaught (in promise) TypeError: Failed to fetch(…)
```

**Comment by eppfel** [comment]
Moved to #280
