### ISSUE TITLE
Reschedule Tasks after ROSE was configured

### ISSUE THREAD

**Issue by eppfel** [secure-software-engineering/rose#228]
So, right now we schedule tasks, when the extension is started, i.e. on browser start / on install.
We have to make sure Tasks can be rescheduled, e.g., when you reset ROSE with a new configuration or when changing the update interval manually.

- [x] Wrap Updater.load() in Promise to trigger reschedule on completion
- [x] Make Execution Service and Tasks possible to reschedule 
- [x] Trigger reschedule of update tasks, when update interval is changed
- [ ] Cancel tasks, when configuration is reset

~~@iamolivinius I will look into this, but the Safari tickets have to be done before.~~

**Comment by dharma-guardian** [comment]
Another thing to reconsider, is the behaviour, that the execution service schedules for the future. So, an interval of one week would leave us in a two week survey with one execution in the middle and one in the end.
That means we intentionally call something and schedule in order to have it execute it right away.

**Comment by dharma-guardian** [comment]
The current behavior also leads to an error, when ROSE is not configured and (re-)started.
```
Unhandled promise rejection TypeError: Cannot read property 'toLowerCase' of null(…)
```
It has to do with the Updater being scheduled, although there is not configuration.

**Comment by dharma-guardian** [comment]
This block in the background script does not consider, whether auto-update is enabled and is execute even without a  configuration. This could lead to no scheduled update until someone restarts their browser.

```JS
const executionService = ExecutionService();
(new SystemConfig()).fetch({
    success: (config) => {
        executionService.schedule(Task({
            name: 'updater',
            rate: config.get('updateInterval'),
            job: Updater.update
        }))
    }
})
```

**Comment by dharma-guardian** [comment]
oh, what's missing now, is to cancel scheduled Tasks, like update and extractors, when the configuration is reset.
