### ISSUE TITLE
Share observer is not working?

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#229]
My "share" (share a post on my timeline) interaction was not recorded. Not sure if it is because the observer is not working or because the "share" observer is not turned on with the default config. Any way to check?

**Comment by dharma-guardian** [comment]
You refer to this dialog?
<img width="544" alt="Screenshot facebook share dialog" src="https://cloud.githubusercontent.com/assets/1899308/12566794/d4459e90-c3bb-11e5-8442-d34c121306b4.png">

I can confirm this. As well as posting a status update on Home / News Feed.
Maybe related to #221 
This is a good opportunity to test observer updates. @iamolivinius is working on observers now, to address possible questions.

**Comment by YiranWangPARC14** [comment]
Yes, I was referring to that kind of action. I tried both "only me", and "on my timeline". Neither was recorded.

**Comment by iamolivinius** [comment]
![screenshot from 2016-02-02 10-43-45](https://cloud.githubusercontent.com/assets/832245/12745513/e3c84de8-c999-11e5-8dff-58c65291618b.png)

"Share now" is identified as unlike-page

**Comment by dharma-guardian** [comment]
Oh, I fu***ed that one up. I recently worked on unlike page, delete post and other observer on these popup menus.
