### ISSUE TITLE
Status update from own timeline isn't recorded

### ISSUE THREAD

**Issue by iamolivinius** [secure-software-engineering/rose#234]
![screenshot from 2016-02-02 11-10-07](https://cloud.githubusercontent.com/assets/832245/12746171/92390dc4-c99d-11e5-8733-10e78b03a4a5.png)

**Comment by dharma-guardian** [comment]
You should have 27 observers, reset ROSE configs and update your observers!

**Comment by dharma-guardian** [comment]
This maybe is the reason for #233

**Comment by iamolivinius** [comment]
yes

**Comment by YiranWangPARC14** [comment]
By "reset ROSE configs and update observers", do you mean manually update the configuration file from the settings?

I just did, but I still only have 25 observers.

<img width="612" alt="screen shot 2016-02-02 at 8 14 05 am" src="https://cloud.githubusercontent.com/assets/3218051/12755645/2b8cbdfe-c985-11e5-8127-90eeee852145.png">

**Comment by YiranWangPARC14** [comment]
Ah nvm... i didn't reset it. Now after reset it and updated the config, i have 27 observers.

**Comment by dharma-guardian** [comment]
Yes, the Updates from the Chrome Webstore do not reset/update the configuration; which is intentional.
