### ISSUE TITLE
Chat observer broken?

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#235]
my chat interactions were not recorded today... can you replicate the problem?

**Comment by iamolivinius** [comment]
can confirm this. looks like they changed/worked on their design a lilttle bit. i assume you're talking about the chat box in the lower right corner, right?

**Comment by YiranWangPARC14** [comment]
Yes, it is the chat box on the bottom right corner.

Is that something that is easy to fix? We just started 10 participants yesterday. It would be great if we can capture ( at least some days of) their chat use. Thanks so much!

**Comment by apoller** [comment]
@iamolivinius Can you fix it and test an updated version of the changed observer. After testing you can add the new observer pattern to the repository and I can sign it

**Comment by iamolivinius** [comment]
Added a new pattern. Left the old one in place in case Facebook did not make the chatbox update gobal yet. Still needs to be signed before @YiranWangPARC14 can run an update.

**Comment by YiranWangPARC14** [comment]
Please let me know what I (and the participants) need to do. Thanks very much!

**Comment by iamolivinius** [comment]
In theory: as soon as Andreas signed the updated pattern file you open ROSE, click Settings in the menu sidebar, and click the Update button in the Manual Configuration Update section. Then reload your facebook page.

**Comment by apoller** [comment]
That's correct. However, as we use a dedicated smartcard for signing the files I can only sign it in my office tomorrow.

**Comment by YiranWangPARC14** [comment]
Ok. Thank you both for solving the problem quickly!

Yiran

On Wed, Feb 10, 2016 at 2:26 PM, apoller <notifications@github.com> wrote:

> That's correct. However, as we use a dedicated smartcard for signing the
> files I can only sign it in my office tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/secure-software-engineering/rose/issues/235#issuecomment-182606631>
> .
>



-- 
Best,
Yiran

**Comment by apoller** [comment]
@iamolivinius Why are you here changing file a file assets/reddit-configuration.json 
while in #236 you are changing two files app/res/defaults/rose-configuration.json and 
assets/reddit-configuration.json? Why does reddit-configuration.json needs to be changed?
Please also remember to link your commits to rose/example/facebook/facebook-observers.json with the respective tickets for making things trackable.

**Comment by apoller** [comment]
Remains open with updater problem described in #236

**Comment by iamolivinius** [comment]
The commits to reddit-configuration.json and rose-configuration.json are not necessary. It's just the fastest way for me to test new patterns locally. Shall I revert these changes?

**Comment by apoller** [comment]
No its okay, just make a respective comment in your commit messages then everything is fine
