### ISSUE TITLE
Status update observer broken?

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#236]
It doesn't work on my side unfortunately...

**Comment by iamolivinius** [comment]
The update-status observer for a user's news feed is broken. I'm working on a fix.

**Comment by iamolivinius** [comment]
Can be closed when new signature is uploaded. Related to #235

**Comment by apoller** [comment]
@iamolivinius 
I updated the signature with ad0f37f  but in my ROSE version the observers are not update. Could you please check it whether it works with your version. I don't get any sensible output in the application log, it only says: 
February 11, 2016 5:44 PM	[{"name":"facebook","updatedExtractors":[],"updatedObservers":[]}]	Updater
Under Settings date remains with  Last Update: Monday, February 1, 2016 5:57 PM

**Comment by iamolivinius** [comment]
Definitely works at my side. I use the reddit config and the default config. After hitting the update button I receive updates for 4 observers, especially the two new patterns I added lately.

```json
{"name":"facebook","updatedExtractors":[],"updatedObservers":[]}
```

This means no updates were available or no updates were performed. In contrast see my log file 

```json
{"name":"facebook","updatedExtractors":[],"updatedObservers":["chat","unlike-content","like-content","share-status"]}
```

**Comment by apoller** [comment]
@YiranWangPARC14 Can you confirm that the tracking package update works on your side?

**Comment by YiranWangPARC14** [comment]
When I used the manual update, it indicated that it wasn't updated. See the screenshot.

<img width="623" alt="screen shot 2016-02-12 at 8 34 06 am" src="https://cloud.githubusercontent.com/assets/3218051/13013397/2786ea36-d164-11e5-8661-60b2cd319c5e.png">

But when I tested the three newly fixed observers, chat, share-status, status-update, they are now recorded correctly. So I guess the update IS working. It is just not shown on the settings page.

**Comment by iamolivinius** [comment]
Check the application log for more detailed information, please.

**Comment by YiranWangPARC14** [comment]
Is this what you are looking for?

<img width="733" alt="screen shot 2016-02-12 at 8 50 29 am" src="https://cloud.githubusercontent.com/assets/3218051/13013763/bd370fba-d165-11e5-9d1c-7016172aa85c.png">
<img width="751" alt="screen shot 2016-02-12 at 8 50 37 am" src="https://cloud.githubusercontent.com/assets/3218051/13013767/c1b72aa2-d165-11e5-8829-21491dc780e2.png">

**Comment by iamolivinius** [comment]
I assume you're using the version from chrome web store, right? Can you send me your configuration file, please?

**Comment by YiranWangPARC14** [comment]
Yes, i am using the chrome store version. I used the default configuration. How do I obtain the config file if I am using the default?

**Comment by iamolivinius** [comment]
OK, I've got the same configuration. Can you send me the link to the chrome web store?

**Comment by YiranWangPARC14** [comment]
https://chrome.google.com/webstore/detail/rose-uc-irvine-version/kgckddgopgbdlpfhjaajknoiiiolenfa

On Fri, Feb 12, 2016 at 10:05 AM, Oliver Hoffmann <notifications@github.com>
wrote:

> OK, I've got the same configuration. Can you send me the link to the
> chrome web store?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/secure-software-engineering/rose/issues/236#issuecomment-183432945>
> .
>



-- 
Best,
Yiran
