### ISSUE TITLE
Share observer is mistakenly labeled as "unlike-page"?

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#237]
When I share something over the private chat box (message), the interaction is correctly recorded as "share-status-chat".

But when I share something to my timeline, the interaction is incorrectly recorded as "unlike-page". 

It looks like the two interactions ("share" and "unlike-page") are currently using the same label "unlike-page", since I just tried to unlike a page, and it was recorded (correctly) as "unlike-page". 

If this is a quick fix (just to change the label name), can you update this and include this update together with the recent changes (#235, #236)? Thank you very much!

**Comment by iamolivinius** [comment]
Seems to be related to this one: https://github.com/secure-software-engineering/rose/issues/229#issuecomment-178477522

**Comment by iamolivinius** [comment]
Please make a screenshot from right before u confirm the interaction. Sharing to your timeline is possible from several places within facebook.

**Comment by YiranWangPARC14** [comment]
Here you go:

![screen shot 2016-02-11 at 2 11 17 pm](https://cloud.githubusercontent.com/assets/3218051/12992462/74b56e18-d0c9-11e5-8923-4518582b948b.png)
![screen shot 2016-02-11 at 2 11 36 pm](https://cloud.githubusercontent.com/assets/3218051/12992469/7baa5fe4-d0c9-11e5-8fb3-8802702523db.png)

**Comment by iamolivinius** [comment]
Oh my gosh! What happened to her eyebrows

**Comment by YiranWangPARC14** [comment]
(my initial reaction was... what happened to her lips... ) nevertheless she is doing a great thing.

**Comment by iamolivinius** [comment]
Take-away: 
Higher priorities (=> +inf) should go with more generic patterns
Lower priorities (=> 0) should go with more specific patterns

@apoller Please update facebook-observers.json.asc as well as facebook-extractors.json.asc

**Comment by apoller** [comment]
Newly signed both files, waiting for confirmation that everything works fine as with #236

**Comment by iamolivinius** [comment]
My results after manual update.

```json
{
  "name":"facebook",
  "updatedExtractors":[
    "status-update"
  ],
  "updatedObservers":[
    "chat",
    "unlike-content",
    "unlike-page",
    "like-content",
    "share-status"
  ]
}
```

**Comment by apoller** [comment]
Should be fixed by now
