### ISSUE TITLE
Share-status and update-status point to the same actions?

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#239]
There are different ways to share a post. But I just found out that using different ways to share yield in different interaction types, even though they refer to the same action. Here is an example:

If I share a post by clicking "share", which will trigger another window on FB to specify how I want to share it. Such share action is recorded as "status-update".

If I share a post by clicking "share post now (friends)", the action is recorded as "share-status".

I don't think the first scenario should be recorded as "status-update". They both should be recorded as "share-status". Is this  related to the discussion earlier about the priority of the observers?

<img width="521" alt="screen shot 2016-02-15 at 10 14 00 pm" src="https://cloud.githubusercontent.com/assets/3218051/13068608/e6ee3bf2-d431-11e5-8e43-7c9c4a500b64.png">

**Comment by iamolivinius** [comment]
That's just a naming issue. @apoller should double check the semantics here before I deploy on update.

**Comment by YiranWangPARC14** [comment]
I see. The problem now is that we can't differentiate the action of someone updating a status and sharing a status if they click "share". I would be great to update this. Thanks very much!

**Comment by apoller** [comment]
Is the effect of both actions basically the same (despite the different accessibility of the shared item, friends only versus all other Facebook users)? I just checked it by my self and I think it is better to call both "share-status".

**Comment by YiranWangPARC14** [comment]
Yes, the effect of the both actions are the same, so calling both "share-status" is more accurate.

**Comment by iamolivinius** [comment]
@apoller Please update signature.

**Comment by YiranWangPARC14** [comment]
I will instruct the participants to update the configuration file to reflect this change. Just to be clear, before clicking the manual configuration update, do they need to click the reset button?

**Comment by iamolivinius** [comment]
No! :no_good:

**Comment by YiranWangPARC14** [comment]
I tested it multiple times after updating the config file . When sharing though "Share" (not "Share Now"), the action is still recorded as "update-status". This is the case even after restarting the browser. Can you check if you can replicate the problem on your end? Thanks!

**Comment by iamolivinius** [comment]
Did the update succeed? What does the application log say about the update process?

**Comment by YiranWangPARC14** [comment]
looks like it did?
<img width="729" alt="screen shot 2016-02-17 at 9 38 01 am" src="https://cloud.githubusercontent.com/assets/3218051/13118672/2dc9075e-d55a-11e5-8f35-1ae9d1da842d.png">

**Comment by YiranWangPARC14** [comment]
OK. I tried again and the share-status is now working correctly. But this time, I did reset the config, and then update it. The log looks like this. I don't know why the updater log at 9:12am look like that, and the 9:40am one look like this. Does this mean we do need to reset it first? confused.

<img width="839" alt="screen shot 2016-02-17 at 9 47 42 am" src="https://cloud.githubusercontent.com/assets/3218051/13118969/95ac4e8e-d55b-11e5-8da8-05f228ecfafd.png">

**Comment by iamolivinius** [comment]
Well.. I forgot to increment the version number of the observers. I just pushed a new observer file and @apoller needs to update the signatures again. Sorry for the delay and the extra work.

**Comment by YiranWangPARC14** [comment]
Ok, thanks. To be clear: once the signature is updated, the participants only need to use the manual updating config without having to resetting it? The reason why it worked for me only after I reset it was because the version number was duplicated?

**Comment by iamolivinius** [comment]
Exactly

**Comment by YiranWangPARC14** [comment]
Just checking to see if the new observers are available to be updated with the correct config version number. Thanks!

**Comment by iamolivinius** [comment]
It's available since this commit: 

https://github.com/secure-software-engineering/rose/issues/239#ref-commit-04eaaf9

**Comment by YiranWangPARC14** [comment]
Thanks!
