### ISSUE TITLE
Problems (confusions) with config update and some observers potentially broken

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#241]
I manually updated my config file 40 minutes ago. First without resetting it (see below), both share-status and status-update were not working.
<img width="828" alt="screen shot 2016-02-18 at 12 50 02 pm" src="https://cloud.githubusercontent.com/assets/3218051/13158156/80fddd1e-d640-11e5-8737-efed8881fb5a.png">

I then reset the config, and update it again (see below). 
<img width="827" alt="screen shot 2016-02-18 at 1 07 28 pm" src="https://cloud.githubusercontent.com/assets/3218051/13158170/9bc2f04e-d640-11e5-894e-338586e1f6a1.png">

Here is what I observe after the update:

- Status update is sometimes not recorded, sometime recorded as "share-status", both incorrect.

- Events related (invite, interested, ignore) actions are not recorded.

I have already instructed 8 participants of this week to update their config file. Can you check if the config file is correct, and the new issues are associated with new observers broken and not the config file update? Thanks!

**Comment by iamolivinius** [comment]
Please provide screenshots of the problematic cases.

**Comment by YiranWangPARC14** [comment]
Event decline not recorded:

<img width="1280" alt="screen shot 2016-02-18 at 2 29 09 pm" src="https://cloud.githubusercontent.com/assets/3218051/13160401/1b82e1f8-d64c-11e5-94cb-ad81c396ea70.png">
<img width="1280" alt="screen shot 2016-02-18 at 2 29 34 pm" src="https://cloud.githubusercontent.com/assets/3218051/13160402/1b884c7e-d64c-11e5-897f-2fca08e30feb.png">

**Comment by YiranWangPARC14** [comment]
update status incorrectly recorded as "share-status"

<img width="524" alt="screen shot 2016-02-18 at 2 30 57 pm" src="https://cloud.githubusercontent.com/assets/3218051/13160449/5a05f4ec-d64c-11e5-98f0-43aaf06d8117.png">
<img width="1280" alt="screen shot 2016-02-18 at 2 31 09 pm" src="https://cloud.githubusercontent.com/assets/3218051/13160450/5a0787ee-d64c-11e5-9006-a3afec4add78.png">

**Comment by YiranWangPARC14** [comment]
Event going not recorded:

<img width="1280" alt="screen shot 2016-02-18 at 2 33 14 pm" src="https://cloud.githubusercontent.com/assets/3218051/13160509/ae0601cc-d64c-11e5-8d7a-80b5152e554d.png">
<img width="1280" alt="screen shot 2016-02-18 at 2 33 41 pm" src="https://cloud.githubusercontent.com/assets/3218051/13160510/ae063a20-d64c-11e5-9929-dcc946fbdd3a.png">

**Comment by YiranWangPARC14** [comment]
I can't seem to re-produce the problem when updating status the action not recorded. Now whenever I update a status, it is recorded as "share-status".

<img width="1280" alt="screen shot 2016-02-18 at 2 37 20 pm" src="https://cloud.githubusercontent.com/assets/3218051/13160613/4b876026-d64d-11e5-8fd5-3d0ee81299fd.png">
<img width="1280" alt="screen shot 2016-02-18 at 2 38 40 pm" src="https://cloud.githubusercontent.com/assets/3218051/13160618/53f03e2c-d64d-11e5-8e67-070bba2978be.png">

**Comment by YiranWangPARC14** [comment]
Event invite not recorded:

<img width="1280" alt="screen shot 2016-02-18 at 2 40 17 pm" src="https://cloud.githubusercontent.com/assets/3218051/13160673/bcffe37c-d64d-11e5-86b6-5e245dbe2993.png">
<img width="1280" alt="screen shot 2016-02-18 at 2 40 35 pm" src="https://cloud.githubusercontent.com/assets/3218051/13160674/bd173630-d64d-11e5-8de7-468803249396.png">

**Comment by iamolivinius** [comment]
The updates should fix all comments in this issues.

**Comment by YiranWangPARC14** [comment]
Thanks!! There still seem to be some glitches with event related actions. I'll open another ticket for that.
