### ISSUE TITLE
Comment on post in event page not recorded

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#243]
I think the event page is changed too. When I commented on a post from an event page, the comment action is not recorded. See the screenshots:

<img width="823" alt="screen shot 2016-02-25 at 4 44 22 pm" src="https://cloud.githubusercontent.com/assets/3218051/13339675/48e2ad3e-dbdf-11e5-8839-0f78a683ea31.png">
<img width="658" alt="screen shot 2016-02-25 at 4 44 54 pm" src="https://cloud.githubusercontent.com/assets/3218051/13339676/48e2d818-dbdf-11e5-9f5f-19e6de0db61b.png">

**Comment by iamolivinius** [comment]
Done :white_check_mark:
