### ISSUE TITLE
New like options are not working again?

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#250]
I tested a few like reactions on FB today (and I made sure the config file was up to date), all the new like reactions (e.g., WOW, sad, love, etc.) were not recorded. All the traditional "like" were recorded correctly.

The screenshots below were the instances where I used the new like reactions, but not recorded in the log

<img width="530" alt="screen shot 2016-03-18 at 11 03 21 am" src="https://cloud.githubusercontent.com/assets/3218051/13867665/3450f546-ecfc-11e5-9ff9-146c36bb50f8.png">
<img width="499" alt="screen shot 2016-03-18 at 11 05 56 am" src="https://cloud.githubusercontent.com/assets/3218051/13867666/346e9f9c-ecfc-11e5-9619-2ee3b777f322.png">
<img width="495" alt="screen shot 2016-03-18 at 11 06 47 am" src="https://cloud.githubusercontent.com/assets/3218051/13867667/346ecd5a-ecfc-11e5-9990-dbfa283b1cfe.png">
<img width="500" alt="screen shot 2016-03-18 at 11 10 25 am" src="https://cloud.githubusercontent.com/assets/3218051/13867668/348cd9bc-ecfc-11e5-8b85-b8d3537cc1e3.png">

**Comment by iamolivinius** [comment]
Can confirm. Facebook changed CSS class names. Fixing it now.

**Comment by YiranWangPARC14** [comment]
@iamolivinius just check in about the ticket:) I'll be back to US in two days and hope to test it before the next batch of participants come in on 3/28. Thanks much!
