### ISSUE TITLE
Share observer not working when "share" with a pop-up window

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#252]
One type of share is not working now. Below are the different ways/places to share, and which ones were recorded and which ones were not recorded.

When "share" and use the pop-up window, ROSE is not recording the interaction. Screenshots below were the three instances where the interaction were not recorded. 1st one was from the Saved page; 2nd one was from my timeline; 3rd one was from a public page.

<img width="956" alt="ss1" src="https://cloud.githubusercontent.com/assets/3218051/14066560/7407e058-f401-11e5-998d-79fb926808b9.png">
<img width="808" alt="ss2" src="https://cloud.githubusercontent.com/assets/3218051/14066558/7407b330-f401-11e5-8808-038046a24877.png">
<img width="998" alt="ss5" src="https://cloud.githubusercontent.com/assets/3218051/14066559/7407c7a8-f401-11e5-8d39-830c04e3dd70.png">

When "share now" or "share as messages", ROSE is working correctly. Screenshots below were the ones that were correctly recorded. 
<img width="541" alt="ss3" src="https://cloud.githubusercontent.com/assets/3218051/14066536/d1426e6a-f400-11e5-9cce-14a3f223c45e.png">
<img width="1001" alt="ss4" src="https://cloud.githubusercontent.com/assets/3218051/14066537/d142be24-f400-11e5-846a-8865286aa46a.png">
<img width="907" alt="ss6" src="https://cloud.githubusercontent.com/assets/3218051/14066545/2174d2f6-f401-11e5-9b4b-83820ce0cb88.png">

This is a little urgent, as my next batch of participants are coming in 3/28 9am (your 3/28 6pm). If this can be fixed before that time, it would be wonderful. If not, I'll tell the participants to update the observer on their own in the middle of the study when it is fixed. Thanks so much again.

**Comment by iamolivinius** [comment]
Update will be available later this day.

**Comment by YiranWangPARC14** [comment]
Works now. Thank you!!!
