### ISSUE TITLE
Status update observer broken again?

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#253]
I updated a status (only text), which was not recorded. I wonder if this is related to #252....

Things always break right before participants come!!! I appreciate speedy recovery in advance!!

**Comment by iamolivinius** [comment]
Update will be available later this day.

**Comment by YiranWangPARC14** [comment]
Thanks for the speedy fix!!! I updated the config a few minutes ago. Then i tried status update. The first 2 were not recorded, but the following ones were recorded. Let me know if i need to update the config again later today?
