### ISSUE TITLE
Researcher Feature: Participant import and CSV Export

### ISSUE THREAD

**Issue by eppfel** [secure-software-engineering/rose#258]

**Comment by iamolivinius** [comment]
what kind of data should be exportable as csv?

- [ ] interactions
- [ ] comments
- [ ] activities
- [ ] extracts
- [ ] diary entries

**Comment by apoller** [comment]
I would start with interactions, comments, diary entries and activities. 

For activities we need a smart way to do this, e.g., the user might enter a interval length (e.g., 2 hours) and the CSV contains the accumulated values for each tracker and for each network for the time intervals.

What do you mean by "extract"?

**Comment by dharma-guardian** [comment]
Extracts are the static data readouts ROSE does periodically.

**Comment by dharma-guardian** [comment]
@YiranWangPARC14 requested a merged table of all actions by time, to relate e.g. activities and interactions. Makes sense to me and should not be to hard to implement. Just on table sorted by timestamps and new columns for each different type of Data and empty cells for the unrelated columns.

**Comment by iamolivinius** [comment]
> all actions

These are?

What about nested data? Don't we have overloaded attribute names?

**Comment by eppfel** [comment]
> These are?

All tables exported before?

> What about nested data? Don't we have overloaded attribute names?

Definitively; I guess we need to use a namespace per table. 

I think this needs further discussion first.
