### ISSUE TITLE
Comment reminder blocks the messenger

### ISSUE THREAD

**Issue by YiranWangPARC14** [secure-software-engineering/rose#259]
I don't need this fixed for my study. But I heard a few participants complaining that the comment reminder at the bottom of the screen blocks parts/all of the messenger box on a computer screen. They couldn't see the last line of what they are typing or see the last line of what the other person is saying.

This may have something to do with the comment reminder message being very long. I wonder if this is not a problem when the reminder message is relatively short.

**Comment by iamolivinius** [comment]
It's a known issue originated from one of ROSE's dependencies. It's already fixed in their code but haven't been released yet. I'll leave this open until semantic-ui publishes a new release.

**Comment by eppfel** [comment]
Fixed in 6dffac110cfdcc5d5767520ee2b523faf19856a0
