### ISSUE TITLE
Error in background script after install

### ISSUE THREAD

**Issue by eppfel** [secure-software-engineering/rose#262]
```
Uncaught (in promise) DOMException: The requested version (1) is less than the existing version (2).
```

**Comment by dharma-guardian** [comment]
[This](http://stackoverflow.com/questions/34336506/chrome-console-error-the-requested-version-1-is-less-than-the-existing-versio) led me to IndexedDB. It seems to be a problem of db versions.
Whats is weird: there is some data written to storage:

```
0	"Interactions"	[]	
1	"install-date"	"2016-05-02T17:55:14.978Z"	
2	"repairInteractions-last-run"	"1462211715715"	
3	"rose-data-version"	"2.0"	
4	"rose-version"	"3.0.0"
```
Build process runs smooth, but ROSE is completely useless on this fresh install.
Chromium Version 49.0.2623.108 Ubuntu 15.10 (64-bit)

**Comment by dharma-guardian** [comment]
Error is thrown in `IDBOpenDBRequest` in `localforage.js` .
You can reproduce the error by executing a localforage request in the console.
e.g. `localforage.setItem("test", "test").then((blob)=>console.log(blob))`

Ruled out the following things. reinstalled npm/bower packages, installed and tested in Google Chrome Stable,

**Comment by iamolivinius** [comment]
Reason might be that Kango relies on an outdated version of localforage.

Solution 1: use outdated in Rose
Solution 2: kick out kango

**Comment by dharma-guardian** [comment]
Thought the same. Going to have another look tomorrow.

Reason might be that Kango relies on an outdated version of localforage.

Solution 1: use outdated in Rose
Solution 2: kick out kango

**Comment by eppfel** [comment]
Installing the rose branch works, so there are breaking changes in the master branch since diversion.
