### ISSUE TITLE
Dashboard misses interactions and extracts

### ISSUE THREAD

**Issue by eppfel** [secure-software-engineering/rose#265]
I did not investigate further, yet, but my dashboard says 112 comments, 0 interactions and 0 extracts, although the respective views show thousands.

The 112 comments are correct.
Added recent interactions, no difference.

**Comment by iamolivinius** [comment]
This is because the data structure of comments and interactions are different. The network attribute for comments is stored at the top level whereas in interactions its stored in a nested field called origin. 

I don't see the point why the location of the network attribute should be different.
