### ISSUE TITLE
Editing comments in ROSE UI strips all but first character...

### ISSUE THREAD

**Issue by eppfel** [secure-software-engineering/rose#266]
... when opening in FB Sidebar afterwards.

Steps to reproduce:

1. Open Facebook
2. Leave ROSE Comment in FB with some text
3. Open ROSE UI and edit said comment
4. Refresh FB and open the same ROSE Comment again
5. Save Comment uneditied

Result: Comment appears stripped in ROSE UI and FB Sidebar

**Comment by iamolivinius** [comment]
This bug wouldn't exist in a typed language :smile_cat: 

At some point in time we had multiple text fields in the sidebar, see: https://github.com/secure-software-engineering/rose/blob/master/app/rose/facebook-ui.js#L189-L192

The current ROSE UI assumes that there is just one textfield for comments.

**Comment by eppfel** [comment]
Ah, thx for dealing with it.

+1 for TypeScript ;)
