### ISSUE TITLE
UI flaw in Study Creator-> Secure Update Function

### ISSUE THREAD

**Issue by apoller** [secure-software-engineering/rose#276]
There is a minor flaw in the Study Creator regarding the secure update function. There exist two radio buttons one labeled "enable Secure update" and another one "Force secure update" both are linked together meaning that I cannot change them independently. Either split their function or remove one of the radio buttons.

**Comment by iamolivinius** [comment]
This is intentional. If you enable "force secure update" it requires that
"secure update" is enabled too. Same is true if you disable "secure update".

**Comment by apoller** [comment]
As far as I understood the semantics of the buttons, it should be possible to "enable secure update" but to disable "force secure update", but it isn't. Both radio buttons are directly linked together which does not make sense in my opinion though I understand the case you describe.

**Comment by iamolivinius** [comment]
Fixed since cfc88f08ff26d9f8bd519c9a0bda44a516addcec
