### ISSUE TITLE
Reopening facebook tab in address bar loads from cache, but without starting content script

### ISSUE THREAD

**Issue by eppfel** [secure-software-engineering/rose#279]
This maybe is an kango error, because the `includes/content.js` is present, but not executed.
## Steps to reproduce:
1. while ROSE is running open a tab with facebook.com
2. close tab
3. open new tab
4. open facebook.com in the addressbar
## Error

No facebook ui loaded

**Comment by iamolivinius** [comment]
Can you create a GIF of a screen recording. Can't reproduce the error.

**Comment by eppfel** [comment]
mh, seems only to occur in my Chromium Version 50.0.2661.102 Built on Ubuntu 15.10, running on Ubuntu 16.04 (64-bit)
Can't reproduce in Google Chrome or on my Mac.
I have to inspect this one a little more....

**Comment by eppfel** [comment]
Not reproducable...
