### ISSUE TITLE
Safari compatiblity and store readieness

### ISSUE THREAD

**Issue by eppfel** [secure-software-engineering/rose#287]
- [x] check if safari works
  - [x] data in settings is ~~not~~ persistent
  - [x] Screenshots in Wizard
  - [x] update triggered but response not shown in UI
- [x] check safari extension requirements
- [x] aquire safari dev license @apoller 

https://safari-extensions.apple.com/

**Comment by apoller** [comment]
Developer account created. Software can be uploaded to Safari Extension Gallery

**Comment by eppfel** [comment]
https://developer.apple.com/app-store/review/guidelines/#extensions
