### ISSUE TITLE
Build and development environment documentation on reference system

### ISSUE THREAD

**Issue by apoller** [secure-software-engineering/rose#298]
Document setting up development tool chain on reference system
- [x] Setup clean Ubuntu 16.04 LTS (reference system)
- [x] Install necessary packages to get a build of ROSE
- [x] Document each step

**Comment by eppfel** [comment]
WIP: https://pad.epp.cloud/JwdgTAJgjCUBwFoCmICsBjBAWdVUICMI4DkCAGAMwEMtVgtjUg==
