### ISSUE TITLE
Add verification in Study Creator

### ISSUE THREAD

**Issue by eppfel** [secure-software-engineering/rose#304]
Right now, even if you provide a fingerprint, the study creator downloads the observer and extractor patterns without any form of verification, which holds an attack vector...

We should not allow selection of patterns, if the fingerprint is set and verification fails.

**Comment by eppfel** [comment]
What do you think? @apoller

**Comment by apoller** [comment]
I don't consider it a security problem as the study creator is for experts and the URL for the repository can be configured there. 

However, I see it more as a usability problem for the researcher using the study creator to create a config file. It would be nice, if the study creator gives any kind of feedback in case the given fingerprint does not match to the signatures provided by the repository specified by the URL. I'm not sure whether it makes sense to block pattern selection. 

Logic-wise, I can imagine that the researcher has to first de-activate the  "Force secure update" option in the study creator before reading unsafe patterns thereby making visible and tangible the intended use of ROSE's security functions. However, in that case ROSE should warn about the unsafe use of repositories.

**Comment by eppfel** [comment]
Yes, I guess there should be feedback and consequently we have to think about the sequence of actions there... I will have a look at it.

**Comment by eppfel** [comment]
While implementing I realized the following: If we have to calculate the fingerprint of the public key to compare it to the entered hash value, would it not make more sense to automatically fill it out, to save time for the researcher. Additionally we give feedback, if there is no key available?
@apoller

**Comment by eppfel** [comment]
fingerprint non-editable, but visually no input field :+1:

**Comment by apoller** [comment]
Adapted translation file with https://github.com/secure-software-engineering/rose/commit/515f505708ccac98605582f095c1720112902ed0 and https://github.com/secure-software-engineering/rose/commit/382237db94aee4c0b560a926db4f9866f72d05ea
