### ISSUE TITLE
Usability ambiguity: Add On/Off indicator at Control Center

### ISSUE THREAD

**Issue by LKocksch** [secure-software-engineering/rose#309]
It is not apperent what status the tracking function is in. See screenshot.
![control center _ onoff](https://cloud.githubusercontent.com/assets/5921719/26556092/ceb8cab0-4498-11e7-8306-14b80eed7a03.png)

**Comment by eppfel** [comment]
Would this suffice?

![kapture 2017-06-06 at 12 25 33](https://cloud.githubusercontent.com/assets/1899308/26824879/4699d086-4ab3-11e7-9ffd-d9f05d19de39.gif)

**Comment by LKocksch** [comment]
Yes. 

But what does "globally" mean?

**Comment by eppfel** [comment]
I guess we can strike it. Does not add anything, that "all" already says...

**Comment by apoller** [comment]
![professor-farnsworth-indeed](https://cloud.githubusercontent.com/assets/5371806/26835649/0b80a120-4ad9-11e7-814d-063622ee251a.jpg)

**Comment by eppfel** [comment]
The label of the toggle shoudl switch from tracking functiuon enabled to tracking function disabled
