### ISSUE TITLE
Study Creator: Hide patterns not intended for configuration by researcher

### ISSUE THREAD

**Issue by apoller** [secure-software-engineering/rose#313]
When retrieving the repository in the study creator, the trackable sites and patterns are shown right below the base file URL. 

At this point it is a bit confusing that some patterns are provided which are only there to implement other patterns, e.g., user-link, chat-user-link. At least I assume that they are meaningless in the configuration context from looking up the respective repository files for Facebook. These patterns should be hidden in the UI, so I suggest to add a respective field to the repository files. 

Are these patterns stored in the configuration file to resolve pattern dependencies even when I unselect them in the creator?

BTW, we might also think about adding a description field providing a short explanation about what the pattern actually tracks. This would certainly improve the usability of the study creator.

**Comment by eppfel** [comment]
Changes in 1d9f8725975ac64a56c24ba7670218f6e3f5f46f

@apoller Can you add the german translation

 +  url: 'periodic',
 +  click: 'click',
 +  input: 'keyboard',
 + studyCreator.patterns: 'Available tracking patterns',

Should we change `click` to `mouse` to make it even more obvious?

This is how it looks now:

<img width="658" alt="bildschirmfoto 2017-05-31 um 15 29 38" src="https://cloud.githubusercontent.com/assets/1899308/26634179/158aa03e-4616-11e7-8985-975b7c590081.png">

---

<img width="687" alt="bildschirmfoto 2017-05-31 um 15 29 53" src="https://cloud.githubusercontent.com/assets/1899308/26634175/131f996c-4616-11e7-8c8b-e1142ee4f4d5.png">
