### ISSUE TITLE
Enable Sourcemaps

### ISSUE THREAD

**Issue by gurkerl83** [secure-software-engineering/rose#44]
Hi, greate extension! Is it possible to enable Sourcemaps in the Gruntfile - I tried and they are getting generated and bundled.

One thing which is quite odd is when I tried to launch the debugger in Chrome and I create a console.log in the code before I get a VM location of the script. 

http://stackoverflow.com/questions/17367560/chrome-development-tool-vm-file-from-javascript

Currently using Webstorm IDE I can connect to Jetbrains Debugging Browser plugin and see the console logs. Here the JS location is different coded like "bin"

Cheers Markus

**Comment by iamolivinius** [comment]
Sourcemaps will be available for the user interface in ROSEv3

**Comment by iamolivinius** [comment]
Fixed since v3
