### ISSUE TITLE
Varying IDs on same object after full page reload

### ISSUE THREAD

**Issue by iamolivinius** [secure-software-engineering/rose#45]
The FacebookLikeObserver returns varying IDs of the same object.

This behavior occurs when you hit the like button, refresh your entire page and hit the like or unlike button again. The result are two different IDs for the same object.

**Comment by dharma-guardian** [comment]
Fixed in 6a0344fbe80f492e4b0903e07bdc570434f60a86 with hashing the URI and not the content itself.
