### ISSUE TITLE
Like: Maybe better name target of liking action "target" instead of object

### ISSUE THREAD

**Issue by apoller** [secure-software-engineering/rose#47]
One thing maybe confusing although we haven't done it different in the past: When liking something there is no item as such created, but the liking action has a specific target with a target owner. However, in the ROSE data, a like is recorded as follows:

{ "index": 7, "deleted": false, "hidden": false, "createdAt": "2014-01-01T19:37:58.056Z", "record": { "object": { "owner": "b8519670", "id": "7c0dd62d", "type": "comment" }, "type": "like" } }

I think it is better to rename "object" into "target" as this better reflects what is recorded.

Any comments or suggestions on that?

**Comment by dharma-guardian** [comment]
Is this still relevant?
