### ISSUE TITLE
Shorten terminal symbols for browser storage

### ISSUE THREAD

**Issue by apoller** [secure-software-engineering/rose#6]
For longitudinal studies we may capture to many data exceeding the extension's browser storage. As a first countermeasure we could replace the long terminal symbols with shorter symbols to save space.

**Comment by dharma-guardian** [comment]
We changed storage to localForage, which stores to IndecedDB. The Limits are much higher there: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API#Storage_limits

**Comment by iamolivinius** [comment]
already fixed #85
