### ISSUE TITLE
Rose misses interactions on posts without comment text

### ISSUE THREAD

**Issue by iamolivinius** [secure-software-engineering/rose#74]
Most of the time, when you share posts of friends or public pages, you do not add any additional text to them. In this cases ROSE fails to record interactions on those posts. See the example screenshot below. I opened my console before I clicked on `like` and `unlike`. Both times no interaction was recorded. 

This is a major issue and needs to be fixed. Otherwise ROSE can not record interactions on posts of people who can be identified as "news recycler".

I think, a similar issue has been discussed in #31 .

![unbenannt](https://f.cloud.github.com/assets/832245/1996155/12d2f97e-8510-11e3-8155-5f7e6817955b.png)

BTW: Do we hash content to resolve our IDs?

**Comment by dharma-guardian** [comment]
Closed in 6a0344fbe80f492e4b0903e07bdc570434f60a86 by Referencing URI.
