### ISSUE TITLE
bug: ROSE saved "delete comment" as "chat"

### ISSUE THREAD

**Issue by akramm** [secure-software-engineering/rose#75]
one of my participants had several "delete comments" in his data set and couldn't recall any of these actions. He suggested he might have edited the comments.

As I followed up the problem I found that when I create a comment, then edit this comment and then delete it, ROSE saves this as "create comment", "create comment", "chat"

**Comment by dharma-guardian** [comment]
Check if still exists, when implemented with new engine in #101
