### ISSUE TITLE
Add option to export data to text file

### ISSUE THREAD

**Issue by LKocksch** [secure-software-engineering/rose#90]

**Comment by iamolivinius** [comment]
Every export is pure text. Every modern operating system has the abilities to read and modify text files.

For a list of text editors, see: http://en.wikipedia.org/wiki/List_of_text_editors

**Comment by dharma-guardian** [comment]
LOL!
I think the problem was, that in v2 you have to copy and paste the data.

**Comment by iamolivinius** [comment]
oh, right! my bad. :)
