### ISSUE TITLE
Rose addresses participants inconsistently "Sie/Du"

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#94]
`rose/app/res/locales/de/translation.json`
"Erzähl uns was Du kommentierst ..."
 "Für wie angemessen halten Sie es ..."
https://github.com/secure-software-engineering/rose/blob/rose-v3/app/res/locales/de/translation.json#L102

**Comment by apoller** [comment]
"Sie" ist besser.
